services:
 postgres:
  container_name: news_db_container
  image: postgres
  restart: always
  environment:
   POSTGRES_DB: news_db
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
  ports:
  - 5436:5432
  volumes:
  - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data: